"use client";
import { Bookmark, ExternalLink, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useMvpWorkspace } from "@/components/levytate-mvp/MvpWorkspaceStore";
import { bootstrapProviderIntelligence } from "@/lib/levytate/provider-intelligence/bootstrap";
import { intelligenceTopics, type IntelligenceTopic, type ProviderIntelligencePayload } from "@/lib/levytate/provider-intelligence/domain";
import { buildFairProviderFeed } from "@/lib/levytate/provider-intelligence/fair-distribution";
const SAVED="levytate-provider-intelligence-saved", FOLLOWING="levytate-provider-intelligence-following";
export function ProviderIntelligenceModule({onOpenProvider}:{onOpenProvider?:(providerId:string)=>void}){
 const {data}=useMvpWorkspace(); const [payload,setPayload]=useState<ProviderIntelligencePayload>({articles:[...bootstrapProviderIntelligence],sources:[],refreshedAt:null,stale:true}); const [topic,setTopic]=useState<IntelligenceTopic>("All"); const [saved,setSaved]=useState<Set<string>>(new Set()); const [following,setFollowing]=useState<Set<string>>(new Set());
 useEffect(()=>{try{setSaved(new Set(JSON.parse(localStorage.getItem(SAVED)||"[]")));setFollowing(new Set(JSON.parse(localStorage.getItem(FOLLOWING)||"[]")));}catch{} fetch("/api/levytate-provider-intelligence").then(r=>r.ok?r.json():null).then(v=>{if(v?.articles?.length){setPayload(v);sessionStorage.setItem("levytate-provider-intelligence-v1",JSON.stringify(v));}}).catch(()=>undefined);},[]);
 const providerMap=useMemo(()=>new Map(data.providers.filter(p=>p.status!=="Archived").map(p=>[p.providerId,p])),[data.providers]); const eligible=payload.articles.filter(a=>providerMap.has(a.providerId)); const feed=buildFairProviderFeed(eligible,{topic}); const toggle=(key:string,current:Set<string>,setter:(v:Set<string>)=>void,storage:string)=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);setter(next);localStorage.setItem(storage,JSON.stringify([...next]));}; const counts={updates:eligible.length,providers:new Set(eligible.map(a=>a.providerId)).size,programmes:eligible.filter(a=>a.contentType==="Programme update").length,guides:eligible.filter(a=>a.contentType==="Employer guide").length};
 return <section className="min-w-0 bg-[#f6f7f4]"><header className="mb-6 border-b border-[#102c3d]/10 pb-5"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#b94f64]">Provider intelligence</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-[#102c3d]">The apprenticeship market, from the source</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#102c3d]/60">Official provider news and programme developments, connected to LevyTate’s canonical provider directory. Open the original source to read the full item.</p><p className="mt-2 flex items-center gap-2 text-xs text-[#102c3d]/45"><RefreshCw size={13}/>{payload.stale?"Using the last known safe cache":"Refreshed cache"}{payload.refreshedAt?` · ${formatDate(payload.refreshedAt)}`:""}</p></header>
 <section className="grid gap-5 border border-[#102c3d]/10 bg-[#102c3d] p-6 text-white md:grid-cols-[1.4fr_1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#82d7c8]">Morning brief</p><h3 className="mt-3 text-2xl font-semibold">{counts.updates} verified updates across {counts.providers} providers</h3><p className="mt-3 text-sm leading-6 text-white/65">This view prioritises fair provider coverage, then freshness. Missing publication dates remain visibly undated rather than being invented.</p></div><dl className="grid grid-cols-2 gap-4">{[[counts.programmes,"programme updates"],[counts.guides,"employer guides"],[counts.providers,"providers covered"],[payload.sources.filter(s=>s.status==="needs-review").length,"sources to review"]].map(([v,l])=><div key={String(l)} className="border-l border-white/20 pl-4"><dt className="text-2xl font-semibold">{v}</dt><dd className="text-xs text-white/55">{l}</dd></div>)}</dl></section>
 <div className="mt-6 flex gap-1 overflow-x-auto border-y border-[#102c3d]/10 py-2">{intelligenceTopics.map(t=><button key={t} onClick={()=>setTopic(t)} className={`min-h-11 shrink-0 border-b-2 px-3 text-xs font-semibold ${topic===t?"border-[#b94f64] text-[#102c3d]":"border-transparent text-[#102c3d]/45"}`}>{t}</button>)}</div>
 <div className="mt-5 grid gap-5 md:grid-cols-2">{feed.map(article=>{const provider=providerMap.get(article.providerId)!;return <article key={article.fingerprint} className="flex flex-col border border-[#102c3d]/10 bg-white p-5 shadow-[0_12px_28px_rgba(16,44,61,.04)]"><div className="flex items-start justify-between gap-3"><button onClick={()=>onOpenProvider?.(article.providerId)} className="text-left"><p className="text-xs font-semibold text-[#0b776e]">{provider.providerName}</p><p className="mt-1 text-[10px] text-[#102c3d]/42">{provider.providerType} · {article.publishedAt?formatDate(article.publishedAt):"Publication date unavailable"}</p></button><button aria-label="Save article" aria-pressed={saved.has(article.fingerprint)} onClick={()=>toggle(article.fingerprint,saved,setSaved,SAVED)} className="grid h-11 w-11 place-items-center"><Bookmark size={16} fill={saved.has(article.fingerprint)?"currentColor":"none"}/></button></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[.15em] text-[#b94f64]">{article.contentType}</p><h3 className="mt-2 text-xl font-semibold leading-tight tracking-[-.025em] text-[#102c3d]">{article.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-[#102c3d]/60">{article.excerpt}</p><div className="mt-5 flex flex-wrap gap-2">{article.topics.map(t=><span key={t} className="bg-[#edf3f0] px-2 py-1 text-[10px] font-semibold text-[#0b776e]">{t}</span>)}</div><div className="mt-5 flex flex-wrap items-center gap-3 border-t border-[#102c3d]/10 pt-4"><a href={article.canonicalUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 bg-[#102c3d] px-4 text-xs font-semibold text-white">Read original <ExternalLink size={13}/></a><button onClick={()=>onOpenProvider?.(article.providerId)} className="min-h-11 text-xs font-semibold text-[#0b776e]">View provider</button><button onClick={()=>toggle(article.providerId,following,setFollowing,FOLLOWING)} className="ml-auto min-h-11 text-xs font-semibold text-[#102c3d]/55">{following.has(article.providerId)?"Following":"Follow"}</button></div></article>})}</div>
 {!feed.length?<div className="mt-5 border border-[#102c3d]/10 bg-white p-10 text-center text-sm text-[#102c3d]/55">No verified provider articles match this topic.</div>:null}<aside className="mt-6 flex gap-3 border-l-2 border-[#0b776e] bg-[#eaf2ee] p-5"><ShieldCheck className="shrink-0 text-[#0b776e]" size={18}/><p className="text-xs leading-5 text-[#102c3d]/60">Fair visibility is deterministic: provider rotation comes before freshness. Ratings, spend, popularity and engagement never influence order.</p></aside></section>;
}
function formatDate(v:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(v));}
