import { bootstrapProviderIntelligence } from "@/lib/levytate/provider-intelligence/bootstrap";
import type { ProviderIntelligenceArticle, ProviderIntelligencePayload, ProviderIntelligenceSource } from "@/lib/levytate/provider-intelligence/domain";
import { enrichProviderArticle, isLikelyProviderArticleUrl, isRelevantProviderArticle, parseProviderDocument } from "@/lib/levytate/provider-intelligence/parsers";
import { assertApprovedProviderUrl, isApprovedProviderUrl } from "@/lib/levytate/provider-intelligence/security";
import { providerIntelligenceSources } from "@/lib/levytate/provider-intelligence/sources";
import { getLevyTateSupabaseConfig, supabaseInsert, supabaseSelect, supabaseUpdate } from "@/lib/server/levytate-supabase";

type ArticleRow={id:string;fingerprint:string;provider_id:string;source_id:string;title:string;excerpt:string;canonical_url:string;image_url:string|null;published_at:string|null;discovered_at:string;content_type:ProviderIntelligenceArticle["contentType"];topics:string[];status:"published"|"hidden"};
const fromRow=(r:ArticleRow):ProviderIntelligenceArticle=>({id:r.id,fingerprint:r.fingerprint,providerId:r.provider_id,sourceId:r.source_id,title:r.title,excerpt:r.excerpt,canonicalUrl:r.canonical_url,imageUrl:r.image_url,publishedAt:r.published_at,discoveredAt:r.discovered_at,contentType:r.content_type,topics:r.topics as ProviderIntelligenceArticle["topics"],status:r.status});
const toRow=(a:ProviderIntelligenceArticle)=>({id:a.id,fingerprint:a.fingerprint,provider_id:a.providerId,source_id:a.sourceId,title:a.title,excerpt:a.excerpt,canonical_url:a.canonicalUrl,image_url:a.imageUrl,published_at:a.publishedAt,discovered_at:a.discoveredAt,content_type:a.contentType,topics:a.topics,status:a.status});
export async function getProviderIntelligence():Promise<ProviderIntelligencePayload>{
 const config=getLevyTateSupabaseConfig(); if(!config)return{articles:[...bootstrapProviderIntelligence],sources:[...providerIntelligenceSources],refreshedAt:null,stale:true};
 try{const q=new URLSearchParams({select:"*",status:"eq.published",order:"published_at.desc.nullslast",limit:"100"});const rows=await supabaseSelect<ArticleRow>(config,"provider_intelligence_articles",q);const sourceRows=await supabaseSelect<ProviderIntelligenceSource & {provider_id:string;source_url:string;provider_domain:string}>(config,"provider_intelligence_sources",new URLSearchParams({select:"*",order:"label"}));const sources=sourceRows.map(row=>({id:row.id,providerId:row.provider_id,label:row.label,sourceUrl:row.source_url,providerDomain:row.provider_domain,parser:row.parser,status:row.status,lastAttemptAt:row.lastAttemptAt??(row as unknown as {last_attempt_at:string|null}).last_attempt_at,lastSuccessfulFetchAt:row.lastSuccessfulFetchAt??(row as unknown as {last_successful_fetch_at:string|null}).last_successful_fetch_at,lastError:row.lastError??(row as unknown as {last_error:string|null}).last_error}));return{articles:rows.map(fromRow),sources,refreshedAt:sources.map(s=>s.lastSuccessfulFetchAt).filter(Boolean).sort().at(-1)??null,stale:false};}catch{return{articles:[...bootstrapProviderIntelligence],sources:[...providerIntelligenceSources],refreshedAt:null,stale:true};}
}
async function fetchDocument(url:string,source:ProviderIntelligenceSource){assertApprovedProviderUrl(url,source);for(let redirect=0;redirect<4;redirect++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url,{redirect:"manual",signal:controller.signal,headers:{"User-Agent":"LevyTate Provider Intelligence/1.0 (+https://levytate.co.uk)",Accept:"application/rss+xml, application/atom+xml, text/html;q=0.9"}});if(response.status>=300&&response.status<400){const next=response.headers.get("location");if(!next)throw new Error("Redirect omitted its destination");url=new URL(next,url).toString();assertApprovedProviderUrl(url,source);continue;}if(!response.ok)throw new Error(`Source returned ${response.status}`);const length=Number(response.headers.get("content-length")||0);if(length>2_000_000)throw new Error("Source response exceeded size limit");const body=await response.text();if(body.length>2_000_000)throw new Error("Source response exceeded size limit");return{body,contentType:response.headers.get("content-type")||""};}finally{clearTimeout(timer);}}throw new Error("Too many redirects");}
async function fetchSource(source:ProviderIntelligenceSource){const index=await fetchDocument(source.sourceUrl,source);const discovered=parseProviderDocument(index.body,source,index.contentType);const enriched:ProviderIntelligenceArticle[]=[];for(let i=0;i<discovered.length;i+=4){enriched.push(...await Promise.all(discovered.slice(i,i+4).map(async article=>{try{const detail=await fetchDocument(article.canonicalUrl,source);return enrichProviderArticle(article,detail.body,source);}catch{return article;}})));}return enriched.filter(isRelevantProviderArticle);}
const comparable=(article:ProviderIntelligenceArticle)=>JSON.stringify({title:article.title,excerpt:article.excerpt,canonicalUrl:article.canonicalUrl,imageUrl:article.imageUrl,publishedAt:article.publishedAt?Date.parse(article.publishedAt):null,contentType:article.contentType,topics:[...article.topics].sort(),status:article.status});
export async function refreshProviderIntelligence(){const config=getLevyTateSupabaseConfig();if(!config)throw new Error("Provider Intelligence storage is unavailable");const active=providerIntelligenceSources.filter(s=>s.status==="active");await supabaseInsert(config,"provider_intelligence_sources",providerIntelligenceSources.map(s=>({id:s.id,provider_id:s.providerId,label:s.label,source_url:s.sourceUrl,provider_domain:s.providerDomain,parser:s.parser,status:s.status})),{query:"on_conflict=id",prefer:"resolution=merge-duplicates,return=minimal"});const outcomes=[];for(let i=0;i<active.length;i+=2){outcomes.push(...await Promise.all(active.slice(i,i+2).map(async source=>{const attemptedAt=new Date().toISOString();try{const articles=(await fetchSource(source)).filter(a=>isApprovedProviderUrl(a.canonicalUrl,source));if(!articles.length)throw new Error("No relevant articles were extracted");const existingRows=await supabaseSelect<ArticleRow>(config,"provider_intelligence_articles",new URLSearchParams({select:"*",source_id:`eq.${source.id}`}));const existingArticles=existingRows.map(fromRow);const hidden=existingArticles.filter(article=>article.status==="published"&&(!isRelevantProviderArticle(article)||!isLikelyProviderArticleUrl(article.canonicalUrl,source)));for(const article of hidden)await supabaseUpdate(config,"provider_intelligence_articles",`fingerprint=eq.${encodeURIComponent(article.fingerprint)}`,{status:"hidden"},{prefer:"return=minimal"});const existing=new Map(existingArticles.map(article=>[article.fingerprint,article]));const inserted=articles.filter(article=>!existing.has(article.fingerprint));const updated=articles.filter(article=>existing.has(article.fingerprint)&&comparable(article)!==comparable(existing.get(article.fingerprint)!));const duplicates=articles.length-inserted.length-updated.length;const changed=[...inserted,...updated];if(changed.length)await supabaseInsert(config,"provider_intelligence_articles",changed.map(toRow),{query:"on_conflict=fingerprint",prefer:"resolution=merge-duplicates,return=minimal"});await supabaseUpdate(config,"provider_intelligence_sources",`id=eq.${encodeURIComponent(source.id)}`,{last_attempt_at:attemptedAt,last_successful_fetch_at:attemptedAt,last_error:null});return{sourceId:source.id,ok:true,discovered:articles.length,inserted:inserted.length,updated:updated.length,duplicates,hidden:hidden.length};}catch(error){await supabaseUpdate(config,"provider_intelligence_sources",`id=eq.${encodeURIComponent(source.id)}`,{last_attempt_at:attemptedAt,last_error:error instanceof Error?error.message.slice(0,300):"Refresh failed"});return{sourceId:source.id,ok:false,discovered:0,inserted:0,updated:0,duplicates:0,hidden:0,error:error instanceof Error?error.message:"Refresh failed"};}})));}return outcomes;}
