import { bootstrapProviderIntelligence } from "@/lib/levytate/provider-intelligence/bootstrap";
import type { ProviderIntelligenceArticle, ProviderIntelligencePayload, ProviderIntelligenceSource } from "@/lib/levytate/provider-intelligence/domain";
import { parseProviderDocument } from "@/lib/levytate/provider-intelligence/parsers";
import { assertApprovedProviderUrl, isApprovedProviderUrl } from "@/lib/levytate/provider-intelligence/security";
import { providerIntelligenceSources } from "@/lib/levytate/provider-intelligence/sources";
import { getLevyTateSupabaseConfig, supabaseInsert, supabaseSelect, supabaseUpdate } from "@/lib/server/levytate-supabase";

type ArticleRow={id:string;fingerprint:string;provider_id:string;source_id:string;title:string;excerpt:string;canonical_url:string;image_url:string|null;published_at:string|null;discovered_at:string;content_type:ProviderIntelligenceArticle["contentType"];topics:string[];status:"published"|"hidden"};
const fromRow=(r:ArticleRow):ProviderIntelligenceArticle=>({id:r.id,fingerprint:r.fingerprint,providerId:r.provider_id,sourceId:r.source_id,title:r.title,excerpt:r.excerpt,canonicalUrl:r.canonical_url,imageUrl:r.image_url,publishedAt:r.published_at,discoveredAt:r.discovered_at,contentType:r.content_type,topics:r.topics as ProviderIntelligenceArticle["topics"],status:r.status});
const toRow=(a:ProviderIntelligenceArticle)=>({id:a.id,fingerprint:a.fingerprint,provider_id:a.providerId,source_id:a.sourceId,title:a.title,excerpt:a.excerpt,canonical_url:a.canonicalUrl,image_url:a.imageUrl,published_at:a.publishedAt,discovered_at:a.discoveredAt,content_type:a.contentType,topics:a.topics,status:a.status});
export async function getProviderIntelligence():Promise<ProviderIntelligencePayload>{
 const config=getLevyTateSupabaseConfig(); if(!config)return{articles:[...bootstrapProviderIntelligence],sources:[...providerIntelligenceSources],refreshedAt:null,stale:true};
 try{const q=new URLSearchParams({select:"*",status:"eq.published",order:"published_at.desc.nullslast",limit:"100"});const rows=await supabaseSelect<ArticleRow>(config,"provider_intelligence_articles",q);return{articles:rows.map(fromRow),sources:[...providerIntelligenceSources],refreshedAt:rows[0]?.discovered_at??null,stale:false};}catch{return{articles:[...bootstrapProviderIntelligence],sources:[...providerIntelligenceSources],refreshedAt:null,stale:true};}
}
async function fetchSource(source:ProviderIntelligenceSource){assertApprovedProviderUrl(source.sourceUrl,source);let url=source.sourceUrl;for(let redirect=0;redirect<4;redirect++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(url,{redirect:"manual",signal:controller.signal,headers:{"User-Agent":"LevyTate Provider Intelligence/1.0 (+https://levytate.co.uk)",Accept:"application/rss+xml, application/atom+xml, text/html;q=0.9"}});if(response.status>=300&&response.status<400){const next=response.headers.get("location");if(!next)throw new Error("Redirect omitted its destination");url=new URL(next,url).toString();assertApprovedProviderUrl(url,source);continue;}if(!response.ok)throw new Error(`Source returned ${response.status}`);const length=Number(response.headers.get("content-length")||0);if(length>2_000_000)throw new Error("Source response exceeded size limit");const body=await response.text();if(body.length>2_000_000)throw new Error("Source response exceeded size limit");return parseProviderDocument(body,source,response.headers.get("content-type")||"");}finally{clearTimeout(timer);}}throw new Error("Too many redirects");}
export async function refreshProviderIntelligence(){const config=getLevyTateSupabaseConfig();if(!config)throw new Error("Provider Intelligence storage is unavailable");const active=providerIntelligenceSources.filter(s=>s.status==="active");await supabaseInsert(config,"provider_intelligence_sources",active.map(s=>({id:s.id,provider_id:s.providerId,label:s.label,source_url:s.sourceUrl,provider_domain:s.providerDomain,parser:s.parser,status:s.status})),{query:"on_conflict=id",prefer:"resolution=merge-duplicates,return=minimal"});const outcomes=[];for(let i=0;i<active.length;i+=4){outcomes.push(...await Promise.all(active.slice(i,i+4).map(async source=>{const attemptedAt=new Date().toISOString();try{const articles=(await fetchSource(source)).filter(a=>isApprovedProviderUrl(a.canonicalUrl,source));if(articles.length)await supabaseInsert(config,"provider_intelligence_articles",articles.map(toRow),{query:"on_conflict=fingerprint",prefer:"resolution=merge-duplicates,return=minimal"});await supabaseUpdate(config,"provider_intelligence_sources",`id=eq.${encodeURIComponent(source.id)}`,{last_attempt_at:attemptedAt,last_successful_fetch_at:attemptedAt,last_error:null});return{sourceId:source.id,ok:true,count:articles.length};}catch(error){await supabaseUpdate(config,"provider_intelligence_sources",`id=eq.${encodeURIComponent(source.id)}`,{last_attempt_at:attemptedAt,last_error:error instanceof Error?error.message.slice(0,300):"Refresh failed"});return{sourceId:source.id,ok:false,count:0};}})));}return outcomes;}
