import type { ProviderIntelligenceArticle } from "./domain.ts";
const a=(v:Omit<ProviderIntelligenceArticle,"id"|"fingerprint"|"discoveredAt"|"status">):ProviderIntelligenceArticle=>({...v,id:`bootstrap-${v.providerId}-${v.publishedAt}`,fingerprint:`${v.providerId}:${v.canonicalUrl}`,discoveredAt:"2026-08-24T08:00:00Z",status:"published"});
export const bootstrapProviderIntelligence:readonly ProviderIntelligenceArticle[]=[
 a({providerId:"provider-qa",sourceId:"source-qa",title:"QA approved to deliver new AI apprenticeship units",excerpt:"QA has been approved to deliver new artificial intelligence apprenticeship units, adding practical AI capability to its employer training offer.",canonicalUrl:"https://www.qa.com/about/news/qa-approved-to-deliver-new-ai-apprenticeship-units/",imageUrl:null,publishedAt:"2026-04-17T00:00:00Z",contentType:"Programme update",topics:["AI & Data","Digital"]}),
 a({providerId:"provider-baltic",sourceId:"source-baltic",title:"Young Apprenticeship Funding Explained",excerpt:"Baltic explains changes to young apprenticeship funding and the practical implications for employers planning future digital skills cohorts.",canonicalUrl:"https://www.balticapprenticeships.com/blog/",imageUrl:null,publishedAt:"2026-08-10T00:00:00Z",contentType:"Policy",topics:["People","Digital"]}),
 a({providerId:"provider-apprentify",sourceId:"source-apprentify",title:"Latest apprenticeship insights from Apprentify",excerpt:"Apprentify publishes practical insight for employers developing digital, data, marketing and leadership capability through apprenticeships.",canonicalUrl:"https://www.apprentify.com/blog/",imageUrl:null,publishedAt:null,contentType:"Insight",topics:["Digital","People"]}),
 a({providerId:"provider-learning-curve-group",sourceId:"source-lcg",title:"Currys launches Urban Driver apprenticeship programme",excerpt:"Learning Curve Group reports on a new employer apprenticeship programme designed to build capability and progression for urban delivery drivers.",canonicalUrl:"https://www.learningcurvegroup.co.uk/news/",imageUrl:null,publishedAt:"2026-08-13T00:00:00Z",contentType:"Employer story",topics:["Operations","People"]}),
 a({providerId:"provider-the-marketing-trainer",sourceId:"source-marketing-trainer",title:"The Marketing Trainer celebrates Ofsted result",excerpt:"The Marketing Trainer shares its latest Ofsted outcome and explains what the result means for learners and employer partners.",canonicalUrl:"https://www.themarketingtrainer.co.uk/blog",imageUrl:null,publishedAt:"2026-06-30T00:00:00Z",contentType:"Performance update",topics:["Commercial","People"]}),
 a({providerId:"provider-hbtc",sourceId:"source-hbtc",title:"Supporting wellbeing and safeguarding: lessons for employers",excerpt:"HBTC shares practical safeguarding and wellbeing considerations for employers supporting apprentices in the workplace.",canonicalUrl:"https://www.hbtc.co.uk/supporting-wellbeing-safeguarding-lessons/",imageUrl:null,publishedAt:"2026-08-05T00:00:00Z",contentType:"Employer guide",topics:["People","Leadership"]}),
 a({providerId:"provider-staffordshire-university",sourceId:"source-staffs",title:"More than 6,000 apprentices trained as university hosts skills summit",excerpt:"University of Staffordshire reports on its apprenticeship contribution and a regional summit focused on workforce skills and employer needs.",canonicalUrl:"https://www.staffs.ac.uk/news/2026/02/more-than-6000-apprentices-trained-as-university-hosts-staffordshire-skills-summit",imageUrl:null,publishedAt:"2026-02-12T00:00:00Z",contentType:"Performance update",topics:["People","Leadership"]}),
 a({providerId:"provider-learning-skills-partnership",sourceId:"source-lsp",title:"Aniksha’s apprenticeship journey",excerpt:"Learning Skills Partnership shares a learner journey showing how structured workplace development can support confidence and progression.",canonicalUrl:"https://www.learningskillspartnership.com/blog",imageUrl:null,publishedAt:"2026-08-20T00:00:00Z",contentType:"Employer story",topics:["People"]}),
 a({providerId:"provider-srscc",sourceId:"source-srscc",title:"Apprenticeship funding changes 2026: what employers need to know",excerpt:"SRSCC explains the withdrawal of selected standards and the implications for employers planning procurement and supply chain apprenticeships.",canonicalUrl:"https://www.srscc.co.uk/news/apprenticeship-funding-changes-2026-what-the-withdrawal-of-key-standards-means-for-employers/",imageUrl:null,publishedAt:"2026-04-20T00:00:00Z",contentType:"Policy",topics:["Procurement","Operations"]}),
];
