import type { IntelligenceProvider, ProviderIntelligenceUpdate } from "./domain.ts";

export const intelligenceProviders: readonly IntelligenceProvider[] = [
  { id: "northstar", name: "Northstar Skills", shortName: "NS", accent: "#0b6f63", premium: true },
  { id: "forge", name: "Forge Learning", shortName: "FL", accent: "#b55268", premium: true },
  { id: "arc", name: "Arc Digital Academy", shortName: "AD", accent: "#315c86", premium: true },
  { id: "civic", name: "Civic Learning Partners", shortName: "CL", accent: "#7b5c39", premium: true },
  { id: "signal", name: "Signal Training", shortName: "ST", accent: "#68528d", premium: true },
  { id: "horizon", name: "Horizon Apprenticeships", shortName: "HA", accent: "#3c7180", premium: true },
  { id: "element", name: "Element Skills", shortName: "ES", accent: "#8a623f", premium: true },
  { id: "atlas", name: "Atlas Learning Group", shortName: "AL", accent: "#47566b", premium: true },
];

const update = (value: ProviderIntelligenceUpdate) => value;

export const providerIntelligenceUpdates: readonly ProviderIntelligenceUpdate[] = [
  update({ id: "ns-1", rawTitle: "Practical AI adoption briefing", displayHeadline: "A practical route from AI interest to workforce capability", displaySummary: "A concise employer briefing on identifying useful AI skills, setting safe learning goals and turning early experiments into repeatable practice.", contentType: "Employer guide", topics: ["AI & Data", "Leadership"], programmes: ["AI Data Specialist", "Data Analyst"], regions: ["National"], providerId: "northstar", publishedAt: "2026-08-12T07:10:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "fg-1", rawTitle: "Operations cohort dates", displayHeadline: "New autumn starts for operations leadership", displaySummary: "Updated cohort dates for employers planning operational leadership development across multi-site teams.", contentType: "Programme update", topics: ["Operations", "Leadership"], programmes: ["Operations Manager"], regions: ["London", "South East"], providerId: "forge", publishedAt: "2026-08-12T06:45:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ar-1", rawTitle: "Digital accessibility session", displayHeadline: "Designing accessible digital services from the outset", displaySummary: "A practitioner session covering inclusive delivery habits for teams building or procuring digital services.", contentType: "Event", topics: ["Digital", "People"], programmes: ["Digital Product Manager"], regions: ["National"], providerId: "arc", publishedAt: "2026-08-11T16:30:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "cv-1", rawTitle: "Procurement standard explainer", displayHeadline: "What the commercial procurement standard means for employers", displaySummary: "An editorial overview of the capabilities, workplace evidence and manager support needed across the programme.", contentType: "Insight", topics: ["Procurement", "Commercial"], programmes: ["Commercial Procurement and Supply"], regions: ["National"], providerId: "civic", publishedAt: "2026-08-11T14:20:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "sg-1", rawTitle: "People manager coaching", displayHeadline: "Building better coaching habits for first-line managers", displaySummary: "Five practical prompts managers can use to make apprenticeship check-ins more focused and useful.", contentType: "Employer guide", topics: ["People", "Leadership"], programmes: ["Team Leader"], regions: ["Midlands", "North West"], providerId: "signal", publishedAt: "2026-08-11T12:05:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "hz-1", rawTitle: "Commercial skills webinar", displayHeadline: "Connecting commercial judgement with customer outcomes", displaySummary: "A live employer discussion about developing confident commercial decision-making in customer-facing teams.", contentType: "Event", topics: ["Commercial", "Leadership"], programmes: ["Chartered Manager"], regions: ["National"], providerId: "horizon", publishedAt: "2026-08-11T10:15:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "el-1", rawTitle: "Data confidence guide", displayHeadline: "A manager’s guide to building everyday data confidence", displaySummary: "How to create safe opportunities for learners to use evidence, challenge assumptions and communicate insight at work.", contentType: "Employer guide", topics: ["AI & Data", "People"], programmes: ["Data Technician"], regions: ["National"], providerId: "element", publishedAt: "2026-08-10T15:40:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "at-1", rawTitle: "Leadership delivery expansion", displayHeadline: "Leadership programme delivery expands into Scotland", displaySummary: "New blended delivery availability for employers with emerging and established managers across Scotland.", contentType: "Programme update", topics: ["Leadership", "Operations"], programmes: ["Team Leader", "Operations Manager"], regions: ["Scotland"], providerId: "atlas", publishedAt: "2026-08-10T13:25:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ns-2", rawTitle: "Data analyst clinic", displayHeadline: "Evidence planning clinic for data analyst apprentices", displaySummary: "A focused clinic helping workplace mentors create meaningful opportunities for analysis and evidence collection.", contentType: "Event", topics: ["AI & Data"], programmes: ["Data Analyst"], regions: ["National"], providerId: "northstar", publishedAt: "2026-08-10T11:10:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "fg-2", rawTitle: "Operational excellence paper", displayHeadline: "Making continuous improvement part of everyday work", displaySummary: "Practical ways for operational teams to connect improvement projects with apprenticeship learning outcomes.", contentType: "Insight", topics: ["Operations"], programmes: ["Improvement Practitioner"], regions: ["National"], providerId: "forge", publishedAt: "2026-08-09T15:00:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ar-2", rawTitle: "Product manager course refresh", displayHeadline: "Digital product programme refreshed for service teams", displaySummary: "The refreshed curriculum places greater emphasis on discovery, accessibility and measurable service outcomes.", contentType: "Programme update", topics: ["Digital", "Commercial"], programmes: ["Digital Product Manager"], regions: ["National"], providerId: "arc", publishedAt: "2026-08-09T12:00:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "cv-2", rawTitle: "Responsible buying session", displayHeadline: "Responsible procurement: turning policy into daily decisions", displaySummary: "An employer session on proportionate due diligence, supplier conversations and evidence apprentices can use.", contentType: "Event", topics: ["Procurement", "Operations"], programmes: ["Commercial Procurement and Supply"], regions: ["National"], providerId: "civic", publishedAt: "2026-08-08T16:20:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "sg-2", rawTitle: "Inclusive teams briefing", displayHeadline: "Inclusive management practices that support learner progress", displaySummary: "A short briefing on psychological safety, clear expectations and adjustments that improve workplace learning.", contentType: "Insight", topics: ["People", "Leadership"], programmes: ["Team Leader"], regions: ["National"], providerId: "signal", publishedAt: "2026-08-08T13:30:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "hz-2", rawTitle: "Sales programme guide", displayHeadline: "Planning meaningful workplace evidence for commercial learners", displaySummary: "Examples of authentic projects that let commercial learners demonstrate customer insight and value creation.", contentType: "Employer guide", topics: ["Commercial"], programmes: ["Sales Executive"], regions: ["South West", "Wales"], providerId: "horizon", publishedAt: "2026-08-08T09:45:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ns-3", rawTitle: "AI governance notes", displayHeadline: "Keeping apprenticeship AI projects useful, safe and accountable", displaySummary: "An editorial note on lightweight governance for workplace AI projects, from data access to human review.", contentType: "Insight", topics: ["AI & Data", "Leadership"], programmes: ["AI Data Specialist"], regions: ["National"], providerId: "northstar", publishedAt: "2026-08-07T16:15:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "fg-3", rawTitle: "Warehouse manager pathway", displayHeadline: "New pathway for managers leading complex warehouse operations", displaySummary: "A delivery pathway designed around shift leadership, safety, performance and continuous improvement.", contentType: "Programme update", topics: ["Operations", "People"], programmes: ["Operations Manager"], regions: ["Midlands", "North West"], providerId: "forge", publishedAt: "2026-08-07T12:40:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ar-3", rawTitle: "Automation discovery workshop", displayHeadline: "Finding worthwhile automation opportunities before choosing tools", displaySummary: "A practical workshop for teams mapping repetitive work and defining the outcome before testing automation.", contentType: "Event", topics: ["Digital", "AI & Data"], programmes: ["Digital Support Technician"], regions: ["National"], providerId: "arc", publishedAt: "2026-08-06T15:05:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ns-4", rawTitle: "Data storytelling field note", displayHeadline: "Helping technical learners communicate insight with clarity", displaySummary: "A field note on audience, evidence and narrative for data apprentices presenting recommendations to leaders.", contentType: "Insight", topics: ["AI & Data", "Commercial"], programmes: ["Data Analyst"], regions: ["National"], providerId: "northstar", publishedAt: "2026-08-06T10:50:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "fg-4", rawTitle: "Lean improvement masterclass", displayHeadline: "A focused masterclass in practical process improvement", displaySummary: "An applied session using workplace problems to explore flow, root causes and sustainable countermeasures.", contentType: "Event", topics: ["Operations"], programmes: ["Improvement Practitioner"], regions: ["North East"], providerId: "forge", publishedAt: "2026-08-05T14:10:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
  update({ id: "ns-5", rawTitle: "AI literacy programme update", displayHeadline: "AI literacy content added across the data pathway", displaySummary: "Updated learning content helps apprentices assess AI outputs, document decisions and recognise common limitations.", contentType: "Programme update", topics: ["AI & Data", "Digital"], programmes: ["Data Technician", "Data Analyst"], regions: ["National"], providerId: "northstar", publishedAt: "2026-08-04T11:20:00Z", sourceType: "Provider editorial", editorialStatus: "published" }),
];

export const marketWatchItems = [
  { label: "Programme updates", count: 3 },
  { label: "Employer guides", count: 4 },
  { label: "Upcoming events", count: 5 },
  { label: "Regional expansions", count: 2 },
  { label: "New insight themes", count: 4 },
] as const;
