import { createHash } from "node:crypto";
import type { IntelligenceContentType, IntelligenceFeedTopic, ProviderIntelligenceArticle, ProviderIntelligenceSource } from "./domain.ts";
import { isApprovedProviderUrl } from "./security";

const decode=(v:string)=>v.replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const excerpt=(v:string)=>{const clean=decode(v); return clean.length<=220?clean:`${clean.slice(0,217).replace(/\s+\S*$/,"")}…`;};
export function classifyArticle(text:string):{contentType:IntelligenceContentType;topics:IntelligenceFeedTopic[]}{const v=text.toLowerCase();const topics:IntelligenceFeedTopic[]=[];if(/ai|data|analytic/.test(v))topics.push("AI & Data");if(/leader|manager/.test(v))topics.push("Leadership");if(/digital|tech/.test(v))topics.push("Digital");if(/operat|supply|logistic/.test(v))topics.push("Operations");if(/commercial|sales|marketing/.test(v))topics.push("Commercial");if(/procurement/.test(v))topics.push("Procurement");if(/people|learner|apprentice|wellbeing/.test(v))topics.push("People");return{contentType:/event|webinar|summit/.test(v)?"Event":/funding|policy|levy|rule/.test(v)?"Policy":/launch|programme|program/.test(v)?"Programme update":"Insight",topics:topics.length?topics:["People"]};}
export function parseProviderDocument(body:string,source:ProviderIntelligenceSource,contentType:string):ProviderIntelligenceArticle[]{
 const items:string[]=[]; const feed=/xml|rss|atom/i.test(contentType)||/<(?:rss|feed)[\s>]/i.test(body);
 if(feed){for(const m of body.matchAll(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi))items.push(m[0]);}else{for(const m of body.matchAll(/<article\b[\s\S]*?<\/article>/gi))items.push(m[0]);}
 const parsed:ProviderIntelligenceArticle[]=[]; for(const block of items.slice(0,30)){const title=decode((block.match(/<title[^>]*>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i)||block.match(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/i)||[])[1]||"");const rawLink=(block.match(/<link[^>]*href=["']([^"']+)/i)||block.match(/<link[^>]*>([^<]+)/i)||block.match(/<a[^>]*href=["']([^"']+)/i)||[])[1]||"";let canonicalUrl="";try{canonicalUrl=new URL(rawLink,source.sourceUrl).toString()}catch{}if(!title||!isApprovedProviderUrl(canonicalUrl,source))continue;const description=(block.match(/<(?:description|summary|content)[^>]*>([\s\S]*?)<\/(?:description|summary|content)>/i)||block.match(/<p[^>]*>([\s\S]*?)<\/p>/i)||[])[1]||title;const rawDate=(block.match(/<(?:pubDate|published|updated|time)[^>]*>([^<]+)/i)||block.match(/datetime=["']([^"']+)/i)||[])[1];const publicationDate=rawDate&&Number.isFinite(Date.parse(rawDate))?new Date(rawDate).toISOString():null;const classified=classifyArticle(`${title} ${description}`);const fingerprint=createHash("sha256").update(`${source.providerId}:${canonicalUrl}`).digest("hex");parsed.push({id:fingerprint.slice(0,24),fingerprint,providerId:source.providerId,sourceId:source.id,title,excerpt:excerpt(description),canonicalUrl,imageUrl:null,publishedAt:publicationDate,discoveredAt:new Date().toISOString(),...classified,status:"published"});}return parsed;
}
