import { createHash } from "node:crypto";
import type { IntelligenceContentType, IntelligenceFeedTopic, ProviderIntelligenceArticle, ProviderIntelligenceSource } from "./domain.ts";
import { isApprovedProviderUrl } from "./security";

const decode=(v:string)=>v.replace(/<[^>]+>/g," ").replace(/&#(x?[0-9a-f]+);/gi,(_,code:string)=>String.fromCodePoint(code[0].toLowerCase()==="x"?Number.parseInt(code.slice(1),16):Number.parseInt(code,10))).replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&ndash;|&mdash;/gi,"–").replace(/\s+/g," ").trim();
const excerpt=(v:string)=>{const clean=decode(v); return clean.length<=220?clean:`${clean.slice(0,217).replace(/\s+\S*$/,"")}…`;};
export function classifyArticle(text:string):{contentType:IntelligenceContentType;topics:IntelligenceFeedTopic[]}{const v=text.toLowerCase();const topics:IntelligenceFeedTopic[]=[];if(/ai|data|analytic/.test(v))topics.push("AI & Data");if(/leader|manager/.test(v))topics.push("Leadership");if(/digital|tech/.test(v))topics.push("Digital");if(/operat|supply|logistic/.test(v))topics.push("Operations");if(/commercial|sales|marketing/.test(v))topics.push("Commercial");if(/procurement/.test(v))topics.push("Procurement");if(/people|learner|apprentice|wellbeing/.test(v))topics.push("People");return{contentType:/event|webinar|summit/.test(v)?"Event":/case study|success stor|journey/.test(v)?"Employer story":/guide|how to|explained/.test(v)?"Employer guide":/funding|policy|levy|rule/.test(v)?"Policy":/launch|programme|program/.test(v)?"Programme update":"Insight",topics:topics.length?topics:["People"]};}
export function isRelevantProviderArticle(article:Pick<ProviderIntelligenceArticle,"providerId"|"title"|"excerpt">){const text=`${article.title} ${article.excerpt}`.toLowerCase();if(article.providerId==="provider-staffordshire-university")return /apprentice|employer|workforce|skills|training/.test(text);return /apprentice|employer|workforce|skills|training|learning|learner|levy|leadership|digital|data|\bai\b|procurement|marketing|supply chain|management/.test(text);}
export function isLikelyProviderArticleUrl(value:string,source:ProviderIntelligenceSource){try{const url=new URL(value);if(!isApprovedProviderUrl(value,source))return false;if(source.id==="source-hbtc")return url.pathname!=="/"&&!/^\/(product|courses?|services?|about|contact)(\/|$)/.test(url.pathname);if(source.id==="source-apprentify")return url.pathname!=="/"&&!/^\/(courses?|programmes?|apprenticeships?)(\/|$)/.test(url.pathname);const base=new URL(source.sourceUrl).pathname.replace(/\/$/,"");return url.pathname.startsWith(`${base}/`)&&url.pathname!==`${base}/`;}catch{return false;}}
function meta(body:string,key:string){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");return (body.match(new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["']`,"i"))||body.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["']`,"i"))||[])[1]||"";}
export function enrichProviderArticle(article:ProviderIntelligenceArticle,body:string,source:ProviderIntelligenceSource):ProviderIntelligenceArticle{const title=decode(meta(body,"og:title")||meta(body,"twitter:title")||article.title);const description=excerpt(meta(body,"og:description")||meta(body,"description")||article.excerpt||title);const rawDate=meta(body,"article:published_time")||(body.match(/"datePublished"\s*:\s*"([^"]+)"/i)||body.match(/<time[^>]+datetime=["']([^"']+)/i)||[])[1]||"";const publishedAt=rawDate&&Number.isFinite(Date.parse(rawDate))?new Date(rawDate).toISOString():article.publishedAt;const rawImage=decode(meta(body,"og:image")||meta(body,"twitter:image"));let imageUrl:string|null=null;if(rawImage)try{const candidate=new URL(rawImage,article.canonicalUrl).toString();if(isApprovedProviderUrl(candidate,source))imageUrl=candidate;}catch{}const classified=classifyArticle(`${title} ${description}`);return{...article,title,excerpt:description,publishedAt,imageUrl,...classified};}
export function parseProviderDocument(body:string,source:ProviderIntelligenceSource,contentType:string):ProviderIntelligenceArticle[]{
 const items:string[]=[]; const feed=/xml|rss|atom/i.test(contentType)||/<(?:rss|feed)[\s>]/i.test(body);
 if(feed){for(const m of body.matchAll(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi))items.push(m[0]);}else{for(const m of body.matchAll(/<article\b[\s\S]*?<\/article>/gi))items.push(m[0]);}
 if(!feed){for(const m of body.matchAll(/<h[2-6][^>]*>([\s\S]*?)<\/h[2-6]>[\s\S]{0,1400}?<a[^>]+href=["']([^"']+)["']/gi))items.push(`<article><h4>${m[1]}</h4><a href="${m[2]}">${m[1]}</a></article>`);for(const m of body.matchAll(/<h[2-6][^>]*>[\s\S]*?<\/h[2-6]>/gi))if(/<a\b/i.test(m[0]))items.push(`<article>${m[0]}</article>`);for(const m of body.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const label=decode(m[2]);let candidate="";try{candidate=new URL(m[1],source.sourceUrl).toString();}catch{}if(label.length>=20&&isLikelyProviderArticleUrl(candidate,source))items.push(`<article><h4>${label}</h4><a href="${candidate}">${label}</a></article>`);}}
 const parsed:ProviderIntelligenceArticle[]=[];const seen=new Set<string>(); for(const block of items.slice(0,100)){const title=decode((block.match(/<title[^>]*>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/title>/i)||block.match(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/i)||[])[1]||"");const rawLink=(block.match(/<link[^>]*href=["']([^"']+)/i)||block.match(/<link[^>]*>([^<]+)/i)||block.match(/<a[^>]*href=["']([^"']+)/i)||[])[1]||"";let canonicalUrl="";try{canonicalUrl=new URL(rawLink,source.sourceUrl).toString()}catch{}if(!title||!isLikelyProviderArticleUrl(canonicalUrl,source)||seen.has(canonicalUrl))continue;const description=(block.match(/<(?:description|summary|content)[^>]*>([\s\S]*?)<\/(?:description|summary|content)>/i)||block.match(/<p[^>]*>([\s\S]*?)<\/p>/i)||[])[1]||title;const rawDate=(block.match(/<(?:pubDate|published|updated|time)[^>]*>([^<]+)/i)||block.match(/datetime=["']([^"']+)/i)||[])[1];const publicationDate=rawDate&&Number.isFinite(Date.parse(rawDate))?new Date(rawDate).toISOString():null;const classified=classifyArticle(`${title} ${description}`);const fingerprint=createHash("sha256").update(`${source.providerId}:${canonicalUrl}`).digest("hex");const article={id:fingerprint.slice(0,24),fingerprint,providerId:source.providerId,sourceId:source.id,title,excerpt:excerpt(description),canonicalUrl,imageUrl:null,publishedAt:publicationDate,discoveredAt:new Date().toISOString(),...classified,status:"published" as const};if(isRelevantProviderArticle(article)){seen.add(canonicalUrl);parsed.push(article);}}return parsed.slice(0,20);
}
