import type { LearnerProgressUpdate, LearnerReview } from "@/lib/levytate/mvp/learner-lifecycle";
import type { ProgressReviewAnalysisInput } from "./progress-review";

const organisationId="00000000-0000-0000-0000-000000000001";
const review=(learnerRecordId:string,id:string,date:string,summary:string,actions:string[]=[],supportRequired=""):LearnerReview=>({id,organisationId,learnerRecordId,reviewType:"provider_review",reviewDate:date,nextReviewDate:"",reviewerName:"Fictional provider reviewer",reviewerUserId:"",providerId:"provider-demo",summary,actions,supportRequired,status:actions.length?"action_required":"completed",createdAt:`${date}T09:00:00Z`,updatedAt:`${date}T09:00:00Z`});
const progress=(learnerRecordId:string,id:string,date:string,target:number,actual:number):LearnerProgressUpdate=>({id,organisationId,learnerRecordId,updateDate:date,targetProgressPercentage:target,actualProgressPercentage:actual,variancePercentage:actual-target,progressSource:"provider_review",sourceReference:id,updatedBy:"fixture",summary:"Fictional validation progress update",supportAction:"",createdAt:`${date}T09:00:00Z`});

export const progressReviewDemoScenarios:ProgressReviewAnalysisInput[]=[
  {organisationId,learnerRecordId:"learner-intel-a",learnerLabel:"Amelia Hart",providerId:"provider-demo",programmeId:"programme-demo",now:"2026-08-24T09:00:00Z",reviews:[review("learner-intel-a","review-a1","2026-04-12","A workplace project opportunity is required.",["Manager to identify workplace project"]),review("learner-intel-a","review-a2","2026-06-14","The workplace project remains outstanding.",["Manager to identify workplace project"]),review("learner-intel-a","review-a3","2026-08-14","Workplace opportunity and manager support remain required.",["Manager to identify workplace project"])],progressUpdates:[progress("learner-intel-a","progress-a1","2026-04-12",40,36),progress("learner-intel-a","progress-a2","2026-06-14",55,46),progress("learner-intel-a","progress-a3","2026-08-14",70,55)]},
  {organisationId,learnerRecordId:"learner-intel-b",learnerLabel:"Daniel Carter",providerId:"provider-demo",now:"2026-08-24T09:00:00Z",reviews:[review("learner-intel-b","review-b1","2026-08-10","The learner is on track and progressing well.")],progressUpdates:[progress("learner-intel-b","progress-b1","2026-08-10",70,54)]},
  {organisationId,learnerRecordId:"learner-intel-c",learnerLabel:"Maya Patel",providerId:"provider-demo",now:"2026-08-24T09:00:00Z",reviews:[review("learner-intel-c","review-c1","2026-06-01","Manager support is required.",["Line manager to provide protected learning time"],"Additional support intervention required"),review("learner-intel-c","review-c2","2026-08-01","Line manager support remains outstanding.",["Line manager to provide protected learning time"],"Additional support intervention remains required")],progressUpdates:[]},
  {organisationId,learnerRecordId:"learner-intel-d",learnerLabel:"Leo Williams",providerId:"provider-demo",now:"2026-08-24T09:00:00Z",reviews:[review("learner-intel-d","review-d1","2026-06-05","Provider to update the learning plan.",["Provider to update learning plan"]),review("learner-intel-d","review-d2","2026-08-05","Provider action to update the learning plan remains outstanding.",["Provider to update learning plan"])],progressUpdates:[]},
  {organisationId,learnerRecordId:"learner-intel-e",learnerLabel:"Sophie Green",providerId:"provider-demo",now:"2026-08-24T09:00:00Z",assessmentReadinessAligned:true,reviews:[review("learner-intel-e","review-e1","2026-08-18","Learner is ready for assessment and gateway evidence is aligned.")],progressUpdates:[progress("learner-intel-e","progress-e1","2026-08-18",80,88)]},
];
