-- Distributed LevyTate authentication abuse controls.
-- This migration is additive and deliberately isolated from employer data.

create table if not exists public.levytate_auth_rate_limits (
  environment_namespace text not null check (environment_namespace in ('local', 'preview', 'production')),
  action text not null check (action ~ '^[a-z0-9_.:-]{1,80}$'),
  key_hash text not null check (key_hash ~ '^[a-f0-9]{64}$'),
  window_start timestamptz not null,
  request_count integer not null default 1 check (request_count > 0),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (environment_namespace, action, key_hash, window_start)
);

create index if not exists levytate_auth_rate_limits_expiry_idx
  on public.levytate_auth_rate_limits (expires_at);

create index if not exists levytate_auth_rate_limits_environment_action_idx
  on public.levytate_auth_rate_limits (environment_namespace, action, updated_at desc);

create table if not exists public.levytate_auth_security_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type ~ '^[a-z0-9_.:-]{1,100}$'),
  environment_namespace text not null check (environment_namespace in ('local', 'preview', 'production')),
  route text not null check (route ~ '^[a-z0-9_./:-]{1,120}$'),
  key_hash text not null check (key_hash ~ '^[a-f0-9]{64}$'),
  outcome_code text not null check (outcome_code ~ '^[a-z0-9_.:-]{1,80}$'),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create index if not exists levytate_auth_security_events_expiry_idx
  on public.levytate_auth_security_events (expires_at);

create index if not exists levytate_auth_security_events_recent_idx
  on public.levytate_auth_security_events (environment_namespace, event_type, created_at desc);

alter table public.levytate_auth_rate_limits enable row level security;
alter table public.levytate_auth_rate_limits force row level security;
alter table public.levytate_auth_security_events enable row level security;
alter table public.levytate_auth_security_events force row level security;

revoke all on table public.levytate_auth_rate_limits from public, anon, authenticated;
revoke all on table public.levytate_auth_security_events from public, anon, authenticated;
grant select, insert, update, delete on table public.levytate_auth_rate_limits to service_role;
grant select, insert, update, delete on table public.levytate_auth_security_events to service_role;
grant usage, select on sequence public.levytate_auth_security_events_id_seq to service_role;

drop policy if exists levytate_auth_rate_limits_service_role_all on public.levytate_auth_rate_limits;
create policy levytate_auth_rate_limits_service_role_all on public.levytate_auth_rate_limits
  for all to service_role
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

drop policy if exists levytate_auth_security_events_service_role_all on public.levytate_auth_security_events;
create policy levytate_auth_security_events_service_role_all on public.levytate_auth_security_events
  for all to service_role
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.levytate_consume_auth_rate_limit(
  p_environment_namespace text,
  p_action text,
  p_key_hash text,
  p_window_seconds integer,
  p_limit integer,
  p_route text,
  p_event_type text default 'authentication_request_rate_limited',
  p_now timestamptz default now()
)
returns table (
  allowed boolean,
  request_count integer,
  remaining integer,
  reset_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window_start timestamptz;
  v_expires_at timestamptz;
  v_count integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_environment_namespace not in ('local', 'preview', 'production')
    or p_action !~ '^[a-z0-9_.:-]{1,80}$'
    or p_key_hash !~ '^[a-f0-9]{64}$'
    or p_route !~ '^[a-z0-9_./:-]{1,120}$'
    or p_event_type !~ '^[a-z0-9_.:-]{1,100}$'
    or p_window_seconds < 1 or p_window_seconds > 86400
    or p_limit < 1 or p_limit > 10000 then
    raise exception 'invalid rate-limit parameters' using errcode = '22023';
  end if;

  delete from public.levytate_auth_rate_limits target
  using (
    select ctid from public.levytate_auth_rate_limits
    where expires_at <= p_now order by expires_at asc limit 25
  ) expired
  where target.ctid = expired.ctid;

  delete from public.levytate_auth_security_events target
  using (
    select ctid from public.levytate_auth_security_events
    where expires_at <= p_now order by expires_at asc limit 25
  ) expired
  where target.ctid = expired.ctid;

  v_window_start := to_timestamp(floor(extract(epoch from p_now) / p_window_seconds) * p_window_seconds);
  v_expires_at := v_window_start + make_interval(secs => p_window_seconds);

  insert into public.levytate_auth_rate_limits as buckets (
    environment_namespace, action, key_hash, window_start, request_count, expires_at, created_at, updated_at
  ) values (
    p_environment_namespace, p_action, p_key_hash, v_window_start, 1, v_expires_at, p_now, p_now
  )
  on conflict (environment_namespace, action, key_hash, window_start)
  do update set
    request_count = least(buckets.request_count + 1, p_limit + 1),
    updated_at = p_now,
    expires_at = excluded.expires_at
  returning buckets.request_count into v_count;

  if v_count = p_limit + 1 then
    insert into public.levytate_auth_security_events (
      event_type, environment_namespace, route, key_hash, outcome_code, created_at
    ) values (
      p_event_type, p_environment_namespace, p_route, p_key_hash, 'threshold_reached', p_now
    );
  end if;

  return query select v_count <= p_limit, v_count, greatest(p_limit - v_count, 0), v_expires_at;
end;
$$;

create or replace function public.levytate_cleanup_auth_rate_limits(
  p_batch_size integer default 1000,
  p_now timestamptz default now()
)
returns table (rate_limits_removed integer, security_events_removed integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_rate_limits_removed integer := 0;
  v_security_events_removed integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_batch_size < 1 or p_batch_size > 10000 then
    raise exception 'invalid cleanup batch size' using errcode = '22023';
  end if;

  with expired as (
    select ctid from public.levytate_auth_rate_limits
    where expires_at <= p_now order by expires_at asc limit p_batch_size
  )
  delete from public.levytate_auth_rate_limits target
  using expired where target.ctid = expired.ctid;
  get diagnostics v_rate_limits_removed = row_count;

  with expired as (
    select ctid from public.levytate_auth_security_events
    where expires_at <= p_now order by expires_at asc limit p_batch_size
  )
  delete from public.levytate_auth_security_events target
  using expired where target.ctid = expired.ctid;
  get diagnostics v_security_events_removed = row_count;

  return query select v_rate_limits_removed, v_security_events_removed;
end;
$$;

revoke all on function public.levytate_consume_auth_rate_limit(text, text, text, integer, integer, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.levytate_cleanup_auth_rate_limits(integer, timestamptz) from public, anon, authenticated;
grant execute on function public.levytate_consume_auth_rate_limit(text, text, text, integer, integer, text, text, timestamptz) to service_role;
grant execute on function public.levytate_cleanup_auth_rate_limits(integer, timestamptz) to service_role;
