-- Provider-neutral LevyTate authentication email delivery evidence.
-- Additive and isolated: no employer, learner, application or membership objects are changed.

create table if not exists public.levytate_auth_email_delivery_events (
  id bigint generated by default as identity primary key,
  environment_namespace text not null check (environment_namespace in ('local', 'preview', 'production')),
  provider text not null check (provider ~ '^[a-z0-9_.:-]{1,40}$'),
  provider_event_id text not null check (char_length(provider_event_id) between 1 and 160),
  provider_message_reference text check (provider_message_reference is null or char_length(provider_message_reference) <= 255),
  authentication_request_reference uuid,
  recipient_hash text not null check (recipient_hash ~ '^[a-f0-9]{64}$'),
  canonical_status text not null check (canonical_status in ('requested', 'accepted', 'delivered', 'delayed', 'bounced', 'rejected', 'complained', 'suppressed', 'failed', 'unknown')),
  provider_event_type text not null check (provider_event_type ~ '^[a-z0-9_.:-]{1,100}$'),
  correlation_confidence text not null check (correlation_confidence in ('exact', 'bounded', 'uncorrelated')),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  processing_status text not null default 'processed' check (processing_status in ('processed', 'ignored', 'failed')),
  safe_failure_code text check (safe_failure_code is null or safe_failure_code ~ '^[a-z0-9_.:-]{1,80}$'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  expires_at timestamptz not null default (now() + interval '90 days'),
  created_at timestamptz not null default now(),
  unique (environment_namespace, provider, provider_event_id)
);

create index if not exists levytate_auth_email_delivery_events_expiry_idx
  on public.levytate_auth_email_delivery_events (expires_at);

create index if not exists levytate_auth_email_delivery_events_message_idx
  on public.levytate_auth_email_delivery_events (environment_namespace, provider_message_reference, occurred_at desc)
  where provider_message_reference is not null;

create index if not exists levytate_auth_email_delivery_events_request_idx
  on public.levytate_auth_email_delivery_events (environment_namespace, authentication_request_reference, occurred_at desc)
  where authentication_request_reference is not null;

create index if not exists levytate_auth_email_delivery_events_recipient_idx
  on public.levytate_auth_email_delivery_events (environment_namespace, recipient_hash, occurred_at desc);

alter table public.levytate_auth_email_delivery_events enable row level security;
alter table public.levytate_auth_email_delivery_events force row level security;

revoke all on table public.levytate_auth_email_delivery_events from public, anon, authenticated;
grant select, insert, update, delete on table public.levytate_auth_email_delivery_events to service_role;
grant usage, select on sequence public.levytate_auth_email_delivery_events_id_seq to service_role;

drop policy if exists levytate_auth_email_delivery_events_service_role_all on public.levytate_auth_email_delivery_events;
create policy levytate_auth_email_delivery_events_service_role_all on public.levytate_auth_email_delivery_events
  for all to service_role
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.levytate_cleanup_auth_email_delivery_events(
  p_batch_size integer default 1000,
  p_now timestamptz default now()
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_removed integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_batch_size < 1 or p_batch_size > 10000 then
    raise exception 'invalid cleanup batch size' using errcode = '22023';
  end if;

  with expired as (
    select ctid from public.levytate_auth_email_delivery_events
    where expires_at <= p_now order by expires_at asc limit p_batch_size
  )
  delete from public.levytate_auth_email_delivery_events target
  using expired where target.ctid = expired.ctid;
  get diagnostics v_removed = row_count;
  return v_removed;
end;
$$;

revoke all on function public.levytate_cleanup_auth_email_delivery_events(integer, timestamptz) from public, anon, authenticated;
grant execute on function public.levytate_cleanup_auth_email_delivery_events(integer, timestamptz) to service_role;

